notification-consumer {
  bootstrapServers = "localhost:9092"
  topic = "todo.events.v1"
  groupId = "todo-notification-consumer-v1"
  consumerName = "todo-notification-consumer-v1"
  dlqTopic = "todo.events.dlq.v1"
  dispatchMode = "sandbox"
  supportedEventVersion = 1
  maxRetries = 3
  retryBackoffMillis = 250

  database {
    driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    url = "jdbc:sqlserver://127.0.0.1:1433;databaseName=ScalaTodoPlayAppDb;encrypt=true;trustServerCertificate=true"
    username = "sa"
    password = "123456"
  }
}
