db.default.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
# Instance adını silip direkt IP ve 1433 portunu yazıyoruz
db.default.url="jdbc:sqlserver://127.0.0.1:1433;databaseName=ScalaTodoPlayAppDb;encrypt=true;trustServerCertificate=true"
db.default.username="sa"
db.default.password="123456"

# Bu iki satırı da ekle ki bağlantı hatalarını daha net görelim
play.db.prototype.hikari.connectionTimeout = 15000
play.db.prototype.hikari.validationTimeout = 5000
play.filters.enabled += "play.filters.csrf.CSRFFilter"
play.http.session.secure = false
play.http.session.httpOnly = true
play.http.session.sameSite = "lax"